### ISSUE TITLE
Breaking songs

### ISSUE THREAD

**Issue by ooTruffle** [BeatLeader/beatleader-qmod#1]
With beatleader enabled any song that uses noodle extensions / chroma will crash beat saber apon trying to load the song with beatleader enabled the songs worked after disabling the mod

This happened on
Quest 2
1.19.1

**Comment by NSGolova** [comment]
Hi, check out the latest commit build https://github.com/BeatLeader/beatleader-qmod/actions/runs/1977490697. Should be fixed

**Comment by H1ghSyst3m** [comment]
Is 2.0 compatible with "1.19.1"?

**Comment by NSGolova** [comment]
> Is 2.0 compatible with "1.19.1"?

Yes, added to the release

**Comment by NSGolova** [comment]
Fixed!
