### ISSUE TITLE
crush when loading the leaderboard

### ISSUE THREAD

**Issue by yoziming** [BeatLeader/beatleader-qmod#13]
Hello, this mod is awosome.But there is some problem.
I got latest version, but it always crush when I preview some map.
I think it's because of the delay in loading the leaderboard, maybe the delay makes some NullPointerException.
Because when I don't show the global rankings, only the local ones, crush almost doesn't happen.
[log.zip](https://github.com/BeatLeader/beatleader-qmod/files/9482442/log.zip)
[tombstone_00.zip](https://github.com/BeatLeader/beatleader-qmod/files/9482443/tombstone_00.zip)

**Comment by NSGolova** [comment]
Hi, is this till happening with the latest release?

**Comment by yoziming** [comment]
Hi bro, I've try latest version 3 days ago and so far no problem.
Thanks for your work.
