### ISSUE TITLE
i got banned?!?!?

### ISSUE THREAD

**Issue by FlamingVR** [BeatLeader/beatleader-qmod#17]
when I was playing tremENDouS (Ranked) I noticed my yesterdays score was not there, so i played it again and BeatLeader said I was banned, I did it with no arrows, my beatleader name is FlamingVR and my VR name is Flaming.VR_ please fix this, i didn't do anything wrong

**Comment by NSGolova** [comment]
![image](https://user-images.githubusercontent.com/8793817/196013033-41d1258b-672e-4e8e-ba6c-712f1fc3a4bd.png)
Default sabers are too short to be able to cut notes at this distance. The ban is temporary and will be removed in a week

**Comment by FlamingVR** [comment]
i use friday night funk sabers at 2.12 length, is that too long??? I use shortaber for it btw. the width of the sabers are 1.08

**Comment by NSGolova** [comment]
of course. Default sabers are 1m long. Your mod should disable score upload for this preference or you will be banned again and for a longer time.
