### ISSUE TITLE
Game Crashing Instantly

### ISSUE THREAD

**Issue by 7v5** [BeatLeader/beatleader-qmod#24]
As soon as i startup my game, it crashes.

**Comment by NSGolova** [comment]
Please provide more info. What are the game and mod versions? What mods have you installed? Qosmetics in particular. Can you send a crash report (from CrashReporter mod or as a files at `sdcard/Android/data/com.beatgames.beatsaber/files/tomstone_01-3`)

**Comment by NSGolova** [comment]
Probably liveness due to Qosmetics coinstalled. The probability of it was reduced in the last release, completely fixing liveness is impossible at this moment
