### ISSUE TITLE
Add Support for Non-Letter/Number Characters ($,@,*) in Passwords

### ISSUE THREAD

**Issue by N0tACyb0rg** [BeatLeader/beatleader-qmod#3]
This would greatly benefit the security of the mod, since passwords would be more secure.

**Comment by christopherweinhardt** [comment]
The current keyboard in beat saber quest doesn't support those characters.

**Comment by kiler129** [comment]
To be more secure using diceware is probably a better approach anyway: https://diceware.dmuth.org
