### ISSUE TITLE
BeatLeader happily accepts JDFixer "No Leaderboard" songs

### ISSUE THREAD

**Issue by KatDevsGames** [BeatLeader/beatleader-qmod#4]
Steps to reproduce:

1: Install BeatLeader and JDFixer.
2: Use JDFixer to change song NJS. (This option should disable score submission!)
3: Play song.

Expected behavior:
Song score is not recorded by BeatLeader.
Song score is not recorded by in-game high score.

Actual behavior:
Song score is submitted to BeatLeader (wrong behavior).
Score does not appear in in-game high score (right behavior).

Issue:
JDFixer lets the player change the JD and NJS but only the JD is supposed to be editable without disabling score submissions. Editing NJS normally disables submissions from being made.

![com beatgames beatsaber-20220502-121802](https://user-images.githubusercontent.com/4085147/166297311-be6303a8-e50d-45e5-9ae3-fbe68de0e2bb.jpg)

**Comment by KleaTech** [comment]
Maybe it should be discussed if NJS modification can be allowed on the leaderboards. Personally I think NJS should be customizable, it's something that I think should have been included in BeatSaber by the devs. There are others who agree with me on this, but I know that there are more who disagree. I'm just saying that this is an opportunity to at least think about this possibility.

**Comment by christopherweinhardt** [comment]
This was fixed and I forgot to close it

**Comment by christopherweinhardt** [comment]
Should be in the next Beat Leader update
