### ISSUE TITLE
I noticed an issue with the new qmod for v 1.35.0

### ISSUE THREAD

**Issue by Morridumdum10** [BeatLeader/beatleader-qmod#41]
The issue is you cannot switch between the beatleader leaderboard and the main game leaderboard like you can on the steam version or beatleader so if you could add support for that then that would be great.

**Comment by Morridumdum10** [comment]
![d974df52626d4b59a3e3477a7e5bb0c9](https://github.com/BeatLeader/beatleader-qmod/assets/169000285/5af03ad2-c14e-4b6c-a751-b1a601ae024a)

**Comment by Morridumdum10** [comment]
On pc beat saber there is an arrow next to the square with a dot in the middle

**Comment by Morridumdum10** [comment]
https://github.com/BeatLeader/beatleader-qmod/assets/169000285/6ad29670-12b7-4bce-8b5c-ea29134885f7

This is it on pc beat saber

**Comment by NSGolova** [comment]
Fixed in the last release

**Comment by Morridumdum10** [comment]
Tysm
