### ISSUE TITLE
Country rank # doesn't update when country is changed. 

### ISSUE THREAD

**Issue by beaudamion** [BeatLeader/beatleader-qmod#42]
If you change your country on the site your rank # doesn't update in game.

**Comment by NSGolova** [comment]
It will update with the next score upload or on the restart. Real-time update is not planned because of the added complexity for such a rare occasion.

**Comment by beaudamion** [comment]
I've updated this multiple times and even on restart / next score upload it doesn't update. It never updates from the original # rank the first country was put in on account creation. Only the location flag updates.
