### ISSUE TITLE
BeatLeader caused crash after every map until I logged it in

### ISSUE THREAD

**Issue by riskable** [BeatLeader/beatleader-qmod#6]
Just an FYI:  If you install the BeatLeader qmod but don't login to a BeatLeader account it'll cause the game to crash pretty reliably after completing any given (modded) map.  Seems like the type of bug that'd be hard for a developer to notice since you're always going to be logging in as yourself and... why would you play a song to completion without logging in first? :smile:

**Comment by NSGolova** [comment]
Fixed👍
