### ISSUE TITLE
Beatsaber (Quest) would consistently freeze after the mod uploads a replay

### ISSUE THREAD

**Issue by Galafador** [BeatLeader/beatleader-qmod#7]
Whenever the mod's done with uploading a replay the game will freeze for 1-2 seconds, sometimes more, and crash the game.
will happen in song select screen and while playing a song too (I suppose the mod keeps uploading the replay in the background)

v0.2.1 for Beatsaber 1.21.0

**Comment by NSGolova** [comment]
Hi, is this still the case with the last release on 1.24?

**Comment by Galafador** [comment]
Hi, I've just updated to 1.24 and this issue no longer happens on this version. Nice.

The game still occasionally crash on song select though...
